using System;
using System.Collections.Generic;
using Bangazon_Financial.Factories;
using Bangazon_Financials.Entities;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Bangazon_Financials_Tests
{
    [TestClass]
    public class ReportTests
    {
        [TestMethod]
        public void ReportsCanBeMade()
        {
            Report testReport = new Report();
            testReport.Name = "Test";
            testReport.Price = 12.34;
            Assert.IsNotNull(testReport);
        }
        [TestMethod]
        public void CanMakeWeeklyReports()
        {
            ReportsFactory repFac = new ReportsFactory();
            List<Report> WeeklyReport = new List<Report>();

            WeeklyReport = repFac.GetWeeklyReports();
            Assert.IsTrue(WeeklyReport.Count >= 0);
            Assert.IsNotNull(WeeklyReport);
        }
        [TestMethod]
        public void CanMakeMonthlyReports()
        {
            ReportsFactory repFac = new ReportsFactory();
            List<Report> MonthlyReports = new List<Report>();

            MonthlyReports = repFac.GetWeeklyReports();
            Assert.IsTrue(MonthlyReports.Count >= 0);
            Assert.IsNotNull(MonthlyReports);
        }
        [TestMethod]
        public void CanMakeQuarterlyReports()
        {
            ReportsFactory repFac = new ReportsFactory();
            List<Report> QuarterlyReports = new List<Report>();

            QuarterlyReports = repFac.GetWeeklyReports();
            Assert.IsTrue(QuarterlyReports.Count >= 0);
            Assert.IsNotNull(QuarterlyReports);
        }
        //Method Name: CanGetRevenueByCustomer
        //Purpose: This methodchecks that a list of reports can be generated by the GetRevenueByCustomer.
        [TestMethod]
        public void CanGetRevenueByCustomer()
        {
            ReportsFactory repFac = new ReportsFactory();
            List<Report> RevenueByCustomer = repFac.GetRevenueByCustomer();

            Assert.IsTrue(RevenueByCustomer.Count > 0);
            Assert.IsNotNull(RevenueByCustomer);
        }
        //Method Name: CanGetRevenueByProduct
        //Purpose: This method checks that a list of reports can be generated by the GetRevenueByProduct.
        [TestMethod]
        public void CanGetRevenueByProduct()
        {
            ReportsFactory repFac = new ReportsFactory();

            List<Report> RevenueByProduct = repFac.GetRevenueByProduct();

            Assert.IsTrue(RevenueByProduct.Count > 0);
            Assert.IsNotNull(RevenueByProduct);
        }
    }
}
